# Generated by Django 3.2.16 on 2023-04-08 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230408_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='card_intro',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(default='tailwind+django.png', upload_to='blog/'),
            preserve_default=False,
        ),
    ]
